@extends('layouts.app', ['title' => 'Order Details'])
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><a class="text-decoration-none" href="{{ route(auth()->user()->role === 'customer' ? 'orders.index' : 'manage.orders.index') }}">Back to orders</a><h1 class="h2 mt-2">{{ $order->order_number }}</h1></div><span class="badge text-bg-primary">{{ ucfirst($order->status) }}</span></div>@if ($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Medicine</th><th>Quantity</th><th>Price</th><th>Subtotal</th></tr></thead><tbody>@foreach ($order->items as $item)<tr><td>{{ $item->medicine_name_snapshot }}</td><td>{{ $item->quantity }}</td><td>Rs {{ number_format((float) $item->unit_price, 2) }}</td><td>Rs {{ number_format((float) $item->subtotal, 2) }}</td></tr>@endforeach</tbody></table></div><div class="card-body border-top"><p class="mb-1">Delivery address: {{ $order->delivery_address }}</p><p class="mb-3">Delivery phone: {{ $order->delivery_phone }}</p><div class="d-flex justify-content-between"><strong>Total</strong><strong>Rs {{ number_format((float) $order->total_amount, 2) }}</strong></div></div></div>@can('updateStatus', $order)<div class="card border-0 shadow-sm mt-4"><div class="card-body"><h2 class="h5">Update order status</h2><form class="d-flex gap-2" method="POST" action="{{ route('manage.orders.status', $order) }}">@csrf @method('PATCH')<select class="form-select" name="status" required><option value="">Select next status</option>@foreach (App\Models\Order::TRANSITIONS[$order->status] ?? [] as $nextStatus)<option value="{{ $nextStatus }}">{{ ucfirst($nextStatus) }}</option>@endforeach</select><button class="btn btn-primary" type="submit">Update</button></form></div></div>@endcan
@if (auth()->user()->role === 'customer' && $order->status === 'delivered' && ! $order->rating)<div class="card border-0 shadow-sm mt-4"><div class="card-body"><h2 class="h5">Rate your experience</h2><form class="row g-3" method="POST" action="{{ route('orders.rating.store', $order) }}">@csrf<div class="col-md-3"><label class="form-label" for="rating">Rating</label><select class="form-select" id="rating" name="rating" required><option value="5">5 - Excellent</option><option value="4">4 - Good</option><option value="3">3 - Average</option><option value="2">2 - Poor</option><option value="1">1 - Very poor</option></select></div><div class="col-md-6"><label class="form-label" for="comment">Comment</label><input class="form-control" id="comment" name="comment" maxlength="1000"></div><div class="col-md-3 d-flex align-items-end"><button class="btn btn-primary w-100" type="submit">Submit rating</button></div></form></div></div>@endif
@can('updateStatus', $order)
	@if (auth()->user()->role === 'admin')
		<div class="card mt-4"><div class="card-body"><h2 class="h5">Assign delivery rider</h2><form class="d-flex gap-2" method="POST" action="{{ route('admin.orders.assign-rider', $order) }}">@csrf<select class="form-select" name="rider_id" required><option value="">Select active rider</option>@foreach (App\Models\User::where('role', 'rider')->where('is_active', true)->get() as $rider)<option value="{{ $rider->id }}" @selected($order->deliveryAssignment?->rider_id === $rider->id)>{{ $rider->name }}</option>@endforeach</select><button class="btn btn-primary" type="submit">Assign rider</button></form></div></div>
	@endif
@endcan
@endsection